### PR TITLE
Support ubuntu gdm3

### LINKED ISSUE #4: Trying to snap raises AttributeError: 'int' object has no attribute 'get_geometry'
I have two issues, The first is minor and likely a mistake on my end after installing/uninstalling several times but I'll add it just in case it is related.

I installed Snappyzones through pip (`python -m pip install snappyzones`) succesfully.
I'm running 5.4.0-128-generic kernel,  Python 3.8.10, using Cinnamon.

My first issue: when trying to run `snappy start` from the command line, I get `bash: /usr/local/bin/snappy: No such file or directory`. Running `which snappy`returns `/home/dieter/.local/bin/snappy`. That executable actually runs, so `/home/dieter/.local/bin/snappy start` works perfect. I've used that to config and save three zones.

Second (real issue): When trying to snap (so pressing and holding left shift, then dragging a window) I get an AttributeError with the following traceback:

```
  File "/home/dieter/.local/bin/snappy", line 8, in <module>
    sys.exit(main())
  File "/home/dieter/.local/lib/python3.8/site-packages/snappyzones/__main__.py", line 23, in main
    launch_background_process(*args, **kwargs)
  File "/home/dieter/.local/lib/python3.8/site-packages/snappyzones/process.py", line 38, in launch_background_process
    service = Service()
  File "/home/dieter/.local/lib/python3.8/site-packages/snappyzones/service.py", line 44, in __init__
    self.display.record_enable_context(self.context, self.handler)
  File "/home/dieter/.local/lib/python3.8/site-packages/Xlib/ext/record.py", line 239, in enable_context
    EnableContext(
  File "/home/dieter/.local/lib/python3.8/site-packages/Xlib/ext/record.py", line 220, in __init__
    rq.ReplyRequest.__init__(self, *args, **keys)
  File "/home/dieter/.local/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/home/dieter/.local/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1381, in reply
    self._display.send_and_recv(request = self._serial)
  File "/home/dieter/.local/lib/python3.8/site-packages/Xlib/protocol/display.py", line 612, in send_and_recv
    gotreq = self.parse_response(request)
  File "/home/dieter/.local/lib/python3.8/site-packages/Xlib/protocol/display.py", line 704, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/home/dieter/.local/lib/python3.8/site-packages/Xlib/protocol/display.py", line 792, in parse_request_response
    req._parse_response(self.data_recv[:self.recv_packet_len])
  File "/home/dieter/.local/lib/python3.8/site-packages/Xlib/ext/record.py", line 224, in _parse_response
    self._callback(r)
  File "/home/dieter/.local/lib/python3.8/site-packages/snappyzones/service.py", line 72, in handler
    shift_window(self, keysym)
  File "/home/dieter/.local/lib/python3.8/site-packages/snappyzones/snap.py", line 46, in shift_window
    pg = window.query_tree().parent.query_tree().parent.get_geometry()
AttributeError: 'int' object has no attribute 'get_geometry'
```

Running `tkinter.TkVersion`from a Python repl returns version 8.6

If there is any more info required, please let me know!

### PR DESCRIPTION
**Pull request by davet2001**
This is the first of a few pull requests I've got lined up.

The existing code does not seem to work with ubuntu Ubuntu 22.04.2 LTS, 

I am no X11/xlib expert, but it looks like this is because the window heirarchy is different in gdm3 compared with what the author was using to develop snappyzones.

For example when traversing the tree to the parent window, in gdm3 you quickly end up at the root window, rather than a 'frame window' containing the elements of interest.

This resolves the issue (or at least gets it closer to a working solution) by detecting the window manager on startup, then triggering different logic. Since I don't have the ability to test the original window manager, this seemed like the safest option.

There are some hardcoded constants in the new code, and I expect these relate to the size of the shadow settings etc in ubuntu. These are based on the default settings, and are just a start point. Perhaps a future PR can calculate precise values somehow by an x11 based measurement or maybe reading the user's config.

This is just a start.

Fixes #4

P.S. I also added some basic logging which will come in useful later.

The follow on PRs that I've got working locally add some graphical enhancements, the main one being a preview of where the window will expand to before the drag is released.

### CODE REVIEW

**Comment by davet2001** [comment]
Update: I've since got rid of my big screen and gone for 3 smaller ones, so this is not such a major issue for me any more.

Also I've found that gSnap offers very similar functionality in ubuntu, and is much more polished, as well as the default UI that offers limited but helpful left/right snapping.

So if someone would like to merge this and continue, they are more than welcome to of course, but my contributions probably won't go beyond this PR. Thanks @mgdotdev for the project in any case!

**Comment by mgdotdev** [comment]
Sorry I didn't see this PR, looks good tho
